class catalog-zero {
   include catalog-zero1
   include catalog-zero1::catalog-zero1-interface2
   include catalog-zero2
   include catalog-zero2::catalog-zero2-interface2
   include catalog-zero3
   include catalog-zero3::catalog-zero3-interface2
   include catalog-zero4
   include catalog-zero4::catalog-zero4-interface2
   include catalog-zero5
   include catalog-zero5::catalog-zero5-interface2
   include catalog-zero6
   include catalog-zero6::catalog-zero6-interface2
   include catalog-zero7
   include catalog-zero7::catalog-zero7-interface2
   include catalog-zero8
   include catalog-zero8::catalog-zero8-interface2
   include catalog-zero9
   include catalog-zero9::catalog-zero9-interface2
   include catalog-zero10
   include catalog-zero10::catalog-zero10-interface2
   include catalog-zero11
   include catalog-zero11::catalog-zero11-interface2
   include catalog-zero12
   include catalog-zero12::catalog-zero12-interface2
   include catalog-zero13
   include catalog-zero13::catalog-zero13-interface2
   include catalog-zero14
   include catalog-zero14::catalog-zero14-interface2
   include catalog-zero15
   include catalog-zero15::catalog-zero15-interface2
   include catalog-zero16
   include catalog-zero16::catalog-zero16-interface2
   include catalog-zero17
   include catalog-zero17::catalog-zero17-interface2
   include catalog-zero18
   include catalog-zero18::catalog-zero18-interface2
   include catalog-zero19
   include catalog-zero19::catalog-zero19-interface2
   include catalog-zero20
   include catalog-zero20::catalog-zero20-interface2
   include catalog-zero21
   include catalog-zero21::catalog-zero21-interface2
   include catalog-zero22
   include catalog-zero22::catalog-zero22-interface2
   include catalog-zero23
   include catalog-zero23::catalog-zero23-interface2
   include catalog-zero24
   include catalog-zero24::catalog-zero24-interface2
   include catalog-zero25
   include catalog-zero25::catalog-zero25-interface2
   include catalog-zero26
   include catalog-zero26::catalog-zero26-interface2
   include catalog-zero27
   include catalog-zero27::catalog-zero27-interface2
   include catalog-zero28
   include catalog-zero28::catalog-zero28-interface2
   include catalog-zero29
   include catalog-zero29::catalog-zero29-interface2
   include catalog-zero30
   include catalog-zero30::catalog-zero30-interface2
}